### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by artem78** [EKA2L1/Dumber#4]
I used dumber on my nokia n95 8gb. The process took much time and there are no any information about progress status (only empty screen). Also after program finished dumping it silently closed without any message. It is a bit confused - user don`t know is the dump in process or something has been wrong. What about show percent of completed during dumping and success message at the end?

**Comment by pent0** [comment]
Ah, Im in the progress of doing it. Also if it exits silently it means crashed:D

**Comment by artem78** [comment]
> Ah, Im in the progress of doing it

Thanks. I will be wait.

**Comment by artem78** [comment]
> Also if it exits silently it means crashed

I retried dumping again and at this time it has been ended with success message. But I can\`t load dump in the emulator. Error in the log:
```
E { eka2l1::loader::determine_rpkg_symbian_version_through_platform_file: Unable to load platform.txt in Z:\Resources\Versions. }
W { eka2l1::loader::determine_rpkg_symbian_version: First method determining Symbian version failed, second one begins }
E { eka2l1::loader::determine_rpkg_product_info_from_platform_txt: Failed to load the file. }
W { eka2l1::loader::determine_rpkg_product_info: First method of determining product info failed, start the second one. }
E { eka2l1::loader::install_rpkg: This device (RM-320) failed to be install, revert all changes }
```
